name: "logs-topology"

config:
  topology.workers: 2
  topology.debug: false
  topology.fall.back.on.java.serialization: false
  topology.max.spout.pending: 10000
  topology.message.timeout.secs: 120
#  topology.kryo.register:
#    - com.github.b0ch3nski.rtla.common.model.SimplifiedLogFrame: "com.github.b0ch3nski.rtla.common.serialization.SimplifiedLogFrameKryoSerializer"
  cassandra.config:
    cassandra.host: "cassandra"
    cassandra.port: 9042
    cassandra.batch.size: 15
    cassandra.flush.time: 30
    cassandra.ttl: 604800
  elasticsearch.config:
    elasticsearch.cluster: "Bochen"
    elasticsearch.unicast.hosts: "es"
    elasticsearch.bulk.actions: "200"
    elasticsearch.bulk.size: "5mb"
    elasticsearch.flush.time: "2m"
    elasticsearch.ttl: "3d"

components:
  - id: "zkHosts"
    className: "storm.kafka.ZkHosts"
    constructorArgs:
      - "zk:2181"

  - id: "logsScheme"
    className: "com.github.b0ch3nski.rtla.storm.spouts.LogsSpoutScheme"

  - id: "logsSpoutConfig"
    className: "storm.kafka.SpoutConfig"
    constructorArgs:
      - ref: "zkHosts"
      - "logs"
      - "/logs-spout-offsets"
      - "logs-spout"
    properties:
      - name: "scheme"
        ref: "logsScheme"

spouts:
  - id: "logs-kafka-spout"
    className: "storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "logsSpoutConfig"
    parallelism: 4

bolts:
  - id: "logs-cassandra-bolt"
    className: "com.github.b0ch3nski.rtla.storm.bolts.LogsCassandraBolt"
    parallelism: 4

  - id: "logs-elasticsearch-bolt"
    className: "com.github.b0ch3nski.rtla.storm.bolts.LogsElasticsearchBolt"
    parallelism: 4

  - id: "logs-counter-bolt"
    className: "com.github.b0ch3nski.rtla.storm.bolts.LogsCounterBolt"
    parallelism: 1

streams:
  - name: "kafka --> cassandra"
    from: "logs-kafka-spout"
    to: "logs-cassandra-bolt"
    grouping:
      type: FIELDS
      args: ["host"]

  - name: "kafka --> elasticsearch"
    from: "logs-kafka-spout"
    to: "logs-elasticsearch-bolt"
    grouping:
      type: FIELDS
      args: ["host"]

  - name: "kafka --> counter"
    from: "logs-kafka-spout"
    to: "logs-counter-bolt"
    grouping:
      type: LOCAL_OR_SHUFFLE
